---
- name: Install Logstash on Ubuntu
  become: yes
  apt:
    deb: /tmp/logstash-6.4.1.deb
    state: present
  notify: Remove package file
  when: ansible_distribution == "Ubuntu"

- name: Install Kibana on CentOS
  become: yes
  yum:
    name: /tmp/logstash-6.4.1.rpm
    state: present
  notify: Remove package file
  when: ansible_distribution == "CentOS"
