---
- name: Copy Logstash package on Ubuntu
  copy:
      src: logstash-6.4.1.deb
      dest: /tmp/logstash-6.4.1.deb
  when: ansible_distribution == "Ubuntu"

- name: Copy Kibana package on CentOS
  copy:
      src: logstash-6.4.1.rpm
      dest: /tmp/logstash-6.4.1.rpm
  when: ansible_distribution == "CentOS"
