---
- name: Check if java is installed
  command: java -version
  register: java_installed
  ignore_errors: True

- name: Copy Java8 dependencies on Ubuntu
  unarchive:
      src: openjdk-8-ubuntu-dep.tar.gz
      dest: /tmp/openjdk-8-ubuntu-dep
  when: ansible_distribution == "Ubuntu" and java_installed is failed

- name: Copy Java8 package on ubuntu
  copy:
      src: openjdk-8-jre-headless_8u181-b13-0ubuntu0.18.04.1_amd64.deb
      dest: /tmp/openjdk-8-ubuntu-dep/openjdk-8-jre-headless_8u181-b13-0ubuntu0.18.04.1_amd64.deb
  when: ansible_distribution == "Ubuntu" and java_installed is failed

- name: Copy Java8 package on CentOS
  copy:
      src: jdk-8u181-linux-x64.rpm
      dest: /tmp/jdk-8u181-linux-x64.rpm
  when: ansible_distribution == "CentOS" and java_installed is failed
