---
- name: Install Kibana on Ubuntu
  become: yes
  apt:
    deb: /tmp/kibana-6.4.1-amd64.deb
    state: present
  notify: Remove package file
  when: ansible_distribution == "Ubuntu"

- name: Install Kibana on CentOS
  become: yes
  yum:
    name: /tmp/kibana-6.4.1-x86_64.rpm
    state: present
  notify: Remove package file
  when: ansible_distribution == "CentOS"
