---
- name: Set JVM heapsize
  become: yes
  template:
          src: jvm.options.j2
          dest: /etc/elasticsearch/jvm.options

- name: Set ES Config file
  become: yes
  template:
          src: elasticsearch.yml.j2
          dest: /etc/elasticsearch/elasticsearch.yml

- name: Set the maximum number of open files to 65536
  become: yes
  lineinfile:
          path: /etc/security/limits.conf
          line: "elasticsearch  -  nofile  65536"
          state: present

- name: Set swappiness to 1 so the system only swaps when absolutly necessary
  become: yes
  shell: sysctl vm.swappiness=1
