---
- name: Copy Elasticsearch package on ubuntu
  copy:
      src: elasticsearch-6.4.1.deb
      dest: /tmp/elasticsearch-6.4.1.deb
  when: ansible_distribution == "Ubuntu"

- name: Copy Elasticsearch package on CentOS
  copy:
      src: elasticsearch-6.4.1.rpm
      dest: /tmp/elasticsearch-6.4.1.rpm
  when: ansible_distribution == "CentOS"

- name: Copy FirewallD service on Centos
  become: yes
  copy:
     src: "{{ item.src }}"
     dest: "{{ item.dest }}"
  with_items:
          - { src: 'elasticsearch.xml', dest: '/usr/lib/firewalld/services/elasticsearch.xml' }
          - { src: 'elasticsearch_transport.xml', dest: '/usr/lib/firewalld/services/elasticsearch_transport.xml' }
  when: ansible_distribution == "CentOS"
  notify: Reload Elasticsearch

- include_tasks: reload_firewall.yml

- name: Enable elasticsearch service on FirewallD
  become: yes
  command: firewall-cmd --zone=public --permanent --add-service=elasticsearch
  when: ansible_distribution == "CentOS"

- name: Enable ES transport service on FirewallD
  become: yes
  command: firewall-cmd --zone=public --permanent --add-service=elasticsearch_transport
  when: ansible_distribution == "CentOS"

- include_tasks: reload_firewall.yml
